version: "3.8"
services:
  front:
    build: .
    volumes:
      - .:/app
      - react-node-modules:/app/node_modules
    command: sh -c "npm start"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  react-node-modules:
